[package]
name = "rust"
version = "0.1.0"
authors = ["Jason Ish <jason.ish@oisf.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.74"

# This points to my plugin branch of Suricata
suricata = { path = "../../suricata/plugins/rust" }
